import Link from "next/link";
import { Footer } from "@/components/layout/footer";

export const metadata = {
  title: "Terms of Service - MindSupport Victoria",
  description: "Terms of service for the MindSupport Victoria platform",
};

export default function TermsPage() {
  return (
    <>
      <div className="max-w-3xl mx-auto px-4 py-12">
        <h1 className="text-3xl font-bold text-foreground mb-2">
          Terms of Service
        </h1>
        <p className="text-sm text-muted-foreground mb-8">
          Last updated: February 2026
        </p>

        <div className="prose prose-sm prose-slate dark:prose-invert max-w-none space-y-6">
          <section>
            <h2 className="text-xl font-semibold text-foreground mt-8 mb-3">
              1. About This Service
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              MindSupport Victoria is a free, AI-powered mental health support
              tool designed for adults (18+) living in Victoria, Australia. This
              service provides general emotional support, coping strategies, and
              connections to professional resources. It is{" "}
              <strong>not a substitute for professional medical advice</strong>,
              diagnosis, or treatment.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mt-8 mb-3">
              2. Important Limitations
            </h2>
            <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
              <li>
                This service uses artificial intelligence. Responses are
                generated by an AI model and may not always be accurate or
                appropriate for your situation.
              </li>
              <li>
                This is not a crisis service. In an emergency, call{" "}
                <a href="tel:000" className="font-bold text-destructive">
                  000
                </a>{" "}
                immediately. For crisis support, contact Lifeline at{" "}
                <a href="tel:131114" className="font-bold text-destructive">
                  13 11 14
                </a>
                .
              </li>
              <li>
                The AI will not provide diagnoses, prescribe medication, or
                replace a qualified mental health professional.
              </li>
              <li>
                This service is not monitored in real-time by human clinicians.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mt-8 mb-3">
              3. Eligibility
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              You must be at least 18 years of age and reside in Victoria,
              Australia to use this service. By creating an account, you confirm
              that you meet these requirements.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mt-8 mb-3">
              4. Your Responsibilities
            </h2>
            <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
              <li>
                You are responsible for maintaining the confidentiality of your
                account credentials.
              </li>
              <li>
                You agree to use this service only for its intended purpose of
                mental health support.
              </li>
              <li>
                You will not attempt to misuse, exploit, or interfere with the
                service.
              </li>
              <li>
                You understand that AI-generated responses should not be treated
                as professional advice.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mt-8 mb-3">
              5. Usage Limits
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              To ensure equitable access and manage costs, usage limits apply: up
              to 20 messages per day and 5 new conversations per week. These
              limits may be adjusted based on service demand.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mt-8 mb-3">
              6. Data Handling
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              Your conversations are stored securely and encrypted in transit.
              Conversation data is used solely to provide continuity in your
              support sessions. For full details, see our{" "}
              <Link href="/privacy" className="text-primary underline">
                Privacy Policy
              </Link>
              .
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mt-8 mb-3">
              7. Crisis Protocols
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              If the AI detects language indicating a potential crisis, it will
              provide emergency contact information and may flag the
              conversation for review. Crisis flags are stored with personally
              identifiable information redacted.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mt-8 mb-3">
              8. Account Deletion
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              You may delete your account at any time through the Settings page.
              Upon deletion, all your data — including conversations, messages,
              and usage logs — will be permanently removed from our systems.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mt-8 mb-3">
              9. Disclaimer of Warranties
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              This service is provided &quot;as is&quot; without warranties of any kind.
              We do not guarantee the accuracy, completeness, or suitability of
              any AI-generated content for your particular circumstances.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mt-8 mb-3">
              10. Changes to These Terms
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              We may update these terms from time to time. Continued use of the
              service constitutes acceptance of the updated terms.
            </p>
          </section>
        </div>

        <div className="mt-12 pt-6 border-t border-border">
          <Link href="/" className="text-sm text-primary hover:underline">
            &larr; Back to home
          </Link>
        </div>
      </div>
      <Footer />
    </>
  );
}
