"use client";

import { Copy, Printer } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export interface HandoffSummary {
  patientContext: string;
  keyThemes: string[];
  emotionalJourney: string;
  copingStrategies: { strategy: string; helpful: boolean | null }[];
  riskFactors: string[];
  recommendations: string[];
  conversationDates: string;
}

function summaryToPlainText(summary: HandoffSummary): string {
  const lines: string[] = [
    "FRED — Handoff Summary for Health Professional",
    `Date range: ${summary.conversationDates}`,
    "",
    "PATIENT CONTEXT",
    summary.patientContext,
    "",
    "KEY THEMES",
    ...summary.keyThemes.map((t) => `• ${t}`),
    "",
    "EMOTIONAL JOURNEY",
    summary.emotionalJourney,
    "",
    "COPING STRATEGIES DISCUSSED",
    ...summary.copingStrategies.map(
      (s) =>
        `• ${s.strategy}${s.helpful === true ? " (found helpful)" : s.helpful === false ? " (not helpful)" : ""}`
    ),
  ];

  if (summary.riskFactors.length > 0) {
    lines.push("", "RISK FACTORS", ...summary.riskFactors.map((r) => `• ${r}`));
  }

  if (summary.recommendations.length > 0) {
    lines.push(
      "",
      "RECOMMENDATIONS",
      ...summary.recommendations.map((r) => `• ${r}`)
    );
  }

  lines.push(
    "",
    "---",
    "Generated by FRED (AI mental health support companion). This summary is not a clinical assessment."
  );

  return lines.join("\n");
}

export function HandoffSummaryView({ summary }: { summary: HandoffSummary }) {
  function handlePrint() {
    window.print();
  }

  async function handleCopy() {
    const text = summaryToPlainText(summary);
    await navigator.clipboard.writeText(text);
  }

  return (
    <div className="space-y-4 print:space-y-2">
      {/* Actions — hidden in print */}
      <div className="flex items-center gap-2 print:hidden">
        <Button variant="outline" size="sm" onClick={handlePrint}>
          <Printer className="h-4 w-4 mr-1" />
          Print
        </Button>
        <Button variant="outline" size="sm" onClick={handleCopy}>
          <Copy className="h-4 w-4 mr-1" />
          Copy to clipboard
        </Button>
      </div>

      {/* Header */}
      <div className="border-b border-border pb-3">
        <h2 className="text-lg font-bold">
          FRED — Handoff Summary for Health Professional
        </h2>
        {summary.conversationDates && (
          <p className="text-sm text-muted-foreground">
            Conversations: {summary.conversationDates}
          </p>
        )}
        <p className="text-xs text-muted-foreground mt-1 italic">
          This summary is generated by an AI support tool and is not a clinical
          assessment.
        </p>
      </div>

      {/* Patient context */}
      <Card>
        <CardHeader className="pb-2">
          <CardTitle className="text-sm">Patient Context</CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-sm">{summary.patientContext}</p>
        </CardContent>
      </Card>

      {/* Key themes */}
      {summary.keyThemes.length > 0 && (
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm">Key Themes</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex flex-wrap gap-1.5">
              {summary.keyThemes.map((theme, i) => (
                <span
                  key={i}
                  className="text-xs rounded-full bg-primary/10 text-primary px-2.5 py-0.5"
                >
                  {theme}
                </span>
              ))}
            </div>
          </CardContent>
        </Card>
      )}

      {/* Emotional journey */}
      {summary.emotionalJourney && (
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm">Emotional Journey</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-sm">{summary.emotionalJourney}</p>
          </CardContent>
        </Card>
      )}

      {/* Coping strategies */}
      {summary.copingStrategies.length > 0 && (
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm">Coping Strategies Discussed</CardTitle>
          </CardHeader>
          <CardContent>
            <ul className="space-y-1">
              {summary.copingStrategies.map((s, i) => (
                <li key={i} className="text-sm flex items-start gap-2">
                  <span className="shrink-0 mt-0.5">
                    {s.helpful === true
                      ? "✓"
                      : s.helpful === false
                        ? "✗"
                        : "–"}
                  </span>
                  <span>
                    {s.strategy}
                    {s.helpful === true && (
                      <span className="text-xs text-green-600 ml-1">
                        (found helpful)
                      </span>
                    )}
                    {s.helpful === false && (
                      <span className="text-xs text-muted-foreground ml-1">
                        (not helpful)
                      </span>
                    )}
                  </span>
                </li>
              ))}
            </ul>
          </CardContent>
        </Card>
      )}

      {/* Risk factors */}
      {summary.riskFactors.length > 0 && (
        <Card className="border-destructive/30">
          <CardHeader className="pb-2">
            <CardTitle className="text-sm text-destructive">
              Risk Factors
            </CardTitle>
          </CardHeader>
          <CardContent>
            <ul className="space-y-1">
              {summary.riskFactors.map((r, i) => (
                <li key={i} className="text-sm">
                  • {r}
                </li>
              ))}
            </ul>
          </CardContent>
        </Card>
      )}

      {/* Recommendations */}
      {summary.recommendations.length > 0 && (
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm">Recommendations</CardTitle>
          </CardHeader>
          <CardContent>
            <ul className="space-y-1">
              {summary.recommendations.map((r, i) => (
                <li key={i} className="text-sm">
                  • {r}
                </li>
              ))}
            </ul>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
